# Generated by Django 5.0.7 on 2024-08-03 19:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=100, verbose_name='نام کلاس')),
                ('class_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='هزینه کلاس')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='نام')),
                ('last_name', models.CharField(max_length=50, verbose_name='نام خانوادگی')),
                ('father_name', models.CharField(max_length=50, verbose_name='نام پدر')),
                ('national_code', models.CharField(max_length=10, unique=True, verbose_name='کد ملی')),
                ('birth_date', models.DateField(verbose_name='تاریخ تولد')),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='مبلغ پرداخت شده')),
                ('contact_number', models.CharField(max_length=15, verbose_name='تلفن تماس')),
                ('classes', models.ManyToManyField(related_name='students', to='Register.class', verbose_name='کلاس\u200cها')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
