# Generated by Django 5.0.7 on 2024-08-04 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0002_alter_class_class_cost_alter_student_payment_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='class_cost',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='هزینه کلاس'),
        ),
        migrations.AlterField(
            model_name='student',
            name='payment_amount',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='مبلغ پرداخت شده'),
        ),
    ]
