# Generated by Django 5.0.7 on 2024-08-06 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0004_student_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='حذف شده'),
        ),
    ]
